import re

import pytest

import checklist_processing
import conversion_settings
import pandoc_converter


def test_checklist_processing_html_to_md_good_html_check_pre_processing():
    html = """<p><input checked="" type="checkbox"/>Check 1</p><p><input type="checkbox"/>Check 2</p><p style="padding-left: 30px;"><input type="checkbox"/>Sub check 1</p><p style="padding-left: 30px;"><input checked="" type="checkbox"/>Sub check 2</p><p style="padding-left: 60px;"><input type="checkbox"/>Sub sub check 1</p><p style="padding-left: 60px;"><input checked="" type="checkbox"/>Sub sub check 2</p><p><input type="checkbox"/>Check 3</p>"""
    checklist_processor = checklist_processing.HTMLInputMDOutputChecklistProcessor(html)

    assert checklist_processor.processed_html.count("checklist-placeholder-id-") == 7


def test_checklist_processing_html_to_md_with_bad_nsx_html_check_pre_processing():
    html = """<div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2</div><div style=\"padding-left: 30px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub Check 1</div><div style=\"padding-left: 30px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 2</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 3</div"""
    checklist_processor = checklist_processing.HTMLInputMDOutputChecklistProcessor(html)

    assert checklist_processor.processed_html.count("checklist-placeholder-id-") == 0


def test_checklist_processing_nsx_to_md_with_clean_html_check_pre_processing():
    html = """<p><input checked="" type="checkbox"/>Check 1</p><p><input type="checkbox"/>Check 2</p><p style="padding-left: 30px;"><input type="checkbox"/>Sub check 1</p><p style="padding-left: 30px;"><input checked="" type="checkbox"/>Sub check 2</p><p style="padding-left: 60px;"><input type="checkbox"/>Sub sub check 1</p><p style="padding-left: 60px;"><input checked="" type="checkbox"/>Sub sub check 2</p><p><input type="checkbox"/>Check 3</p>"""
    checklist_processor = checklist_processing.NSXInputMDOutputChecklistProcessor(html)

    assert checklist_processor.processed_html.count("checklist-placeholder-id-") == 7


def test_checklist_processing_nsx_to_md_with_nsx_html_check_pre_processing():
    html = """<div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2</div><div style=\"padding-left: 30px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub Check 1</div><div style=\"padding-left: 30px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 2</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 3</div"""
    checklist_processor = checklist_processing.NSXInputMDOutputChecklistProcessor(html)

    assert checklist_processor.processed_html.count("checklist-placeholder-id-") == 5


@pytest.mark.parametrize(
    'html, expected', [
        ('<div><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2</div><div style=\"padding-left: 30px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 1</div><div style=\"padding-left: 30px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 2</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 1</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 2</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 3</div>',
         '<div>checklist-placeholder-id- Check 1</div><div>checklist-placeholder-id- Check 2</div><div style="padding-left: 30px;">checklist-placeholder-id- Sub check 1</div><div style="padding-left: 30px;">checklist-placeholder-id- Sub check 2</div><div style="padding-left: 60px;">checklist-placeholder-id- Sub sub check 1</div><div style="padding-left: 60px;">checklist-placeholder-id- Sub sub check 2</div><div>checklist-placeholder-id- Check 3</div>'),
        ('<div><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 1</div><div style=\"padding-left: 30px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 2</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 1</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 2</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 3</div>',
         r'<div>checklist-placeholder-id- Check 1</div><div>checklist-placeholder-id- Check 2</div><div style="padding-left: 60px;">checklist-placeholder-id- Sub check 1</div><div style="padding-left: 30px;">checklist-placeholder-id- Sub check 2</div><div style="padding-left: 60px;">checklist-placeholder-id- Sub sub check 1</div><div style="padding-left: 60px;">checklist-placeholder-id- Sub sub check 2</div><div>checklist-placeholder-id- Check 3</div>'),
        ('<div><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2</div><div style=\"padding-left: 30px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 1</div><div style=\"padding-left: 30px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 2</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 1</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 2</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 3</div>',
         r'<div>checklist-placeholder-id- Check 1</div><div>checklist-placeholder-id- Check 2</div><div style="padding-left: 30px;">checklist-placeholder-id- Sub check 1</div><div style="padding-left: 30px;">checklist-placeholder-id- Sub check 2</div><div style="padding-left: 60px;">checklist-placeholder-id- Sub sub check 1</div><div style="padding-left: 60px;">checklist-placeholder-id- Sub sub check 2</div><div>checklist-placeholder-id- Check 3</div>'),
        ('<div><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2</div><div style=\"padding-left: 45px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 1</div><div style=\"padding-left: 30px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 2</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 1</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 2</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 3</div>',
         r'<div>checklist-placeholder-id- Check 1</div><div>checklist-placeholder-id- Check 2</div><div style="padding-left: 45px;">checklist-placeholder-id- Sub check 1</div><div style="padding-left: 30px;">checklist-placeholder-id- Sub check 2</div><div style="padding-left: 60px;">checklist-placeholder-id- Sub sub check 1</div><div style="padding-left: 60px;">checklist-placeholder-id- Sub sub check 2</div><div>checklist-placeholder-id- Check 3</div>'),
        ('<div><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2</div><div style=\"padding-left: 30px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 1</div><div style=\"padding-left: 90px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 2</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 1</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 2</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 3</div>',
         r'<div>checklist-placeholder-id- Check 1</div><div>checklist-placeholder-id- Check 2</div><div style="padding-left: 30px;">checklist-placeholder-id- Sub check 1</div><div style="padding-left: 90px;">checklist-placeholder-id- Sub check 2</div><div style="padding-left: 60px;">checklist-placeholder-id- Sub sub check 1</div><div style="padding-left: 60px;">checklist-placeholder-id- Sub sub check 2</div><div>checklist-placeholder-id- Check 3</div>'),
        ('<input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />',
         '<p>checklist-placeholder-id-</p>'),
        ('<input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1<input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2',
         'checklist-placeholder-id- Check 1<p>checklist-placeholder-id- Check 2</p>'),
        ('<input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1<input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2<input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 3',
         'checklist-placeholder-id- Check 1<p>checklist-placeholder-id- Check 2</p><p>checklist-placeholder-id- Check 3</p>'),
        ('<ul><li><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1</li><li><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2</li><li><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 3</li></ul>',
         '<ul><li>checklist-placeholder-id- Check 1</li><li>checklist-placeholder-id- Check 2</li><li>checklist-placeholder-id- Check 3</li></ul>'),
        ('<ul><li><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1<ul><li><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2 <a href="http://www.google.com">google.com</a></li></ul></li><li><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 3<a href="mailto:fake@fake.com">fake@fake.com</a></li></ul>',
         '<ul><li>checklist-placeholder-id- Check 1<ul><li>checklist-placeholder-id- Check 2 <a href="http://www.google.com">google.com</a></li></ul></li><li>checklist-placeholder-id- Check 3<a href="mailto:fake@fake.com">fake@fake.com</a></li></ul>'),
        ]
)
def test_checklist_pre_processing_nsx_to_md_with_nsx_html_markdown_output(html, expected):
    checklist_processor = checklist_processing.NSXInputMDOutputChecklistProcessor(html)

    result = checklist_processor.processed_html

    regex = r"\d{15}"  # used to replace the placeholder id number
    sub_with = ""
    compare_to, subs_made = re.subn(regex, sub_with, result, 0, re.MULTILINE)

    assert compare_to == expected


@pytest.mark.parametrize(
    'html, expected', [
        ('<div><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2</div><div style=\"padding-left: 30px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 1</div><div style=\"padding-left: 30px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 2</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 1</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 2</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 3</div>',
         '- [x] Check 1\n\n- [ ] Check 2\n\n\t- [ ] Sub check 1\n\n	- [x] Sub check 2\n\n\t\t- [ ] Sub sub check 1\n\n\t\t- [x] Sub sub check 2\n\n- [ ] Check 3\n'),
        ('<div><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 1</div><div style=\"padding-left: 30px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 2</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 1</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 2</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 3</div>',
         '- [x] Check 1\n\n- [ ] Check 2\n\n\t\t- [ ] Sub check 1\n\n	- [x] Sub check 2\n\n\t\t- [ ] Sub sub check 1\n\n\t\t- [x] Sub sub check 2\n\n- [ ] Check 3\n'),
        ('<div><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2</div><div style=\"padding-left: 30px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 1</div><div style=\"padding-left: 30px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 2</div><div style=\"padding-left: 445px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 1</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 2</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 3</div>',
         '- [x] Check 1\n\n- [ ] Check 2\n\n\t- [ ] Sub check 1\n\n	- [x] Sub check 2\n\n\t\t\t- [ ] Sub sub check 1\n\n\t\t- [x] Sub sub check 2\n\n- [ ] Check 3\n'),
        ('<div><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2</div><div style=\"padding-left: 45px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 1</div><div style=\"padding-left: 30px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 2</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 1</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 2</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 3</div>',
         '- [x] Check 1\n\n- [ ] Check 2\n\n\t\t- [ ] Sub check 1\n\n	- [x] Sub check 2\n\n\t\t\t- [ ] Sub sub check 1\n\n\t\t\t- [x] Sub sub check 2\n\n- [ ] Check 3\n'),
        ('<div><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2</div><div style=\"padding-left: 30px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 1</div><div style=\"padding-left: 90px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 2</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 1</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 2</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 3</div>',
         '- [x] Check 1\n\n- [ ] Check 2\n\n\t- [ ] Sub check 1\n\n\t\t\t- [x] Sub check 2\n\n\t\t- [ ] Sub sub check 1\n\n\t\t- [x] Sub sub check 2\n\n- [ ] Check 3\n'),
        ('<input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />',
         '- [x]\n'),
        ('<input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1<input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2',
         '- [x] Check 1\n\n\t- [ ] Check 2\n'),
        ('<input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1<input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2<input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 3',
         '- [x] Check 1\n\n\t- [ ] Check 2\n\n\t- [ ] Check 3\n'),
        ('<ul><li><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1</li><li><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2</li><li><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 3</li></ul>',
         '- [x] Check 1\n- [ ] Check 2\n- [ ] Check 3\n'),
        ('<ul><li><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1<ul><li><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2 <a href="http://www.google.com">google.com</a></li></ul></li><li><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 3 <a href="mailto:fake@fake.com">fake@fake.com</a></li></ul>',
         '- [x] Check 1\n    - [ ] Check 2 [google.com](http://www.google.com)\n- [ ] Check 3 <fake@fake.com>\n'),
        ]
)
def test_checklist_post_processing_nsx_to_md_with_nsx_html_markdown_output(html, expected):
    checklist_processor = checklist_processing.NSXInputMDOutputChecklistProcessor(html)
    cs = conversion_settings.ConversionSettings()
    pandoc_processor = pandoc_converter.PandocConverter(cs)

    pre_processed = checklist_processor.processed_html
    # clean excessive divs as yanom does
    pre_processed = pre_processed.replace('<div></div>', '<p></p>')
    pre_processed = pre_processed.replace('<div', '<p')
    pre_processed = pre_processed.replace('</div', '</p')

    converted_content = pandoc_processor.convert_using_strings(pre_processed, 'fake_note')
    result = checklist_processor.checklist_post_processing(converted_content)
    assert result == expected


@pytest.mark.parametrize(
    'html, expected', [
        ('<div><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2</div><div style=\"padding-left: 30px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 1</div><div style=\"padding-left: 30px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 2</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 1</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 2</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 3</div>',
         '<div><input checked="" type="checkbox"/>Check 1</div><div><input type="checkbox"/>Check 2</div><div style="padding-left: 30px;"><input type="checkbox"/>Sub check 1</div><div style="padding-left: 30px;"><input checked="" type="checkbox"/>Sub check 2</div><div style="padding-left: 60px;"><input type="checkbox"/>Sub sub check 1</div><div style="padding-left: 60px;"><input checked="" type="checkbox"/>Sub sub check 2</div><div><input type="checkbox"/>Check 3</div>'),
        ('<div><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 1</div><div style=\"padding-left: 30px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 2</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 1</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 2</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 3</div>',
         '<div><input checked="" type="checkbox"/>Check 1</div><div><input type="checkbox"/>Check 2</div><div style="padding-left: 60px;"><input type="checkbox"/>Sub check 1</div><div style="padding-left: 30px;"><input checked="" type="checkbox"/>Sub check 2</div><div style="padding-left: 60px;"><input type="checkbox"/>Sub sub check 1</div><div style="padding-left: 60px;"><input checked="" type="checkbox"/>Sub sub check 2</div><div><input type="checkbox"/>Check 3</div>'),
        ('<div><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2</div><div style=\"padding-left: 30px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 1</div><div style=\"padding-left: 30px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 2</div><div style=\"padding-left: 445px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 1</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 2</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 3</div>',
         '<div><input checked="" type="checkbox"/>Check 1</div><div><input type="checkbox"/>Check 2</div><div style="padding-left: 30px;"><input type="checkbox"/>Sub check 1</div><div style="padding-left: 30px;"><input checked="" type="checkbox"/>Sub check 2</div><div style="padding-left: 445px;"><input type="checkbox"/>Sub sub check 1</div><div style="padding-left: 60px;"><input checked="" type="checkbox"/>Sub sub check 2</div><div><input type="checkbox"/>Check 3</div>'),
        ('<div><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2</div><div style=\"padding-left: 45px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 1</div><div style=\"padding-left: 30px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 2</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 1</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 2</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 3</div>',
         '<div><input checked="" type="checkbox"/>Check 1</div><div><input type="checkbox"/>Check 2</div><div style="padding-left: 45px;"><input type="checkbox"/>Sub check 1</div><div style="padding-left: 30px;"><input checked="" type="checkbox"/>Sub check 2</div><div style="padding-left: 60px;"><input type="checkbox"/>Sub sub check 1</div><div style="padding-left: 60px;"><input checked="" type="checkbox"/>Sub sub check 2</div><div><input type="checkbox"/>Check 3</div>'),
        ('<div><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2</div><div style=\"padding-left: 30px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 1</div><div style=\"padding-left: 90px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub check 2</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 1</div><div style=\"padding-left: 60px;\"><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Sub sub check 2</div><div><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 3</div>',
         '<div><input checked="" type="checkbox"/>Check 1</div><div><input type="checkbox"/>Check 2</div><div style="padding-left: 30px;"><input type="checkbox"/>Sub check 1</div><div style="padding-left: 90px;"><input checked="" type="checkbox"/>Sub check 2</div><div style="padding-left: 60px;"><input type="checkbox"/>Sub sub check 1</div><div style="padding-left: 60px;"><input checked="" type="checkbox"/>Sub sub check 2</div><div><input type="checkbox"/>Check 3</div>'),
        ('<input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />',
         '<input checked="" type="checkbox"/>'),
        ('<input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1<input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2',
         '<input checked="" type="checkbox"/>Check 1<input type="checkbox"/>Check 2'),
        ('<input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1<input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2<input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 3',
         '<input checked="" type="checkbox"/>Check 1<input type="checkbox"/>Check 2<input type="checkbox"/>Check 3'),
        ('<ul><li><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1</li><li><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2</li><li><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 3</li></ul>',
         '<ul><li><input checked="" type="checkbox"/>Check 1</li><li><input type="checkbox"/>Check 2</li><li><input type="checkbox"/>Check 3</li></ul>'),
        ('<ul><li><input class=\"syno-notestation-editor-checkbox syno-notestation-editor-checkbox-checked\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 1<ul><li><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 2 <a href="http://www.google.com">google.com</a></li></ul></li><li><input class=\"syno-notestation-editor-checkbox\" src=\"webman/3rdparty/NoteStation/images/transparent.gif\" type=\"image\" />Check 3 <a href="mailto:fake@fake.com">fake@fake.com</a></li></ul>',
         '<ul><li><input checked="" type="checkbox"/>Check 1<ul><li><input type="checkbox"/>Check 2 <a href="http://www.google.com">google.com</a></li></ul></li><li><input type="checkbox"/>Check 3 <a href="mailto:fake@fake.com">fake@fake.com</a></li></ul>'),
        ('<ul><li><input checked="" type="checkbox"/>Check 1<ul><li><input type="checkbox"/>Check 2 <a href="http://www.google.com">google.com</a></li></ul></li><li><input type="checkbox"/>Check 3 <a href="mailto:fake@fake.com">fake@fake.com</a></li></ul>',
         '<ul><li><input checked="" type="checkbox"/>Check 1<ul><li><input type="checkbox"/>Check 2 <a href="http://www.google.com">google.com</a></li></ul></li><li><input type="checkbox"/>Check 3 <a href="mailto:fake@fake.com">fake@fake.com</a></li></ul>'),
        ]
)
def test_checklist_ptr_processing_nsx_to_html_with_nsx_html_markdown_output(html, expected):
    checklist_processor = checklist_processing.NSXInputHTMLOutputChecklistProcessor(html)
    cs = conversion_settings.ConversionSettings()

    result = checklist_processor.processed_html

    assert result == expected


@pytest.mark.parametrize(
    'html, expected_indent', [
        ('<div><input type="checkbox"/>Check 1</div><div><input type="checkbox"/>Check 1</div><input type="checkbox"/>Check 1</div>',
         0),
        ('<div><input type="checkbox"/>Check 1</div><div><input type="checkbox"/>Check 1</div><div style=\"padding-left: 30px;\"><input type="checkbox"/>sub check 1</div>',
         1),
        ('<div><input type="checkbox"/>Check 1</div><div><input type="checkbox"/>Check 1</div><div style=\"padding-right: 30px;\"><input type="checkbox"/>sub check 1</div>',
         0),
        ('<div><input type="checkbox"/>Check 1</div><div style=\"padding-left: 30px;\"><input type="checkbox"/>Check2<input type="checkbox"/>sub check 1</div>',
         2),
        ('<div><input type="checkbox"/>Check 1</div><div><input type="checkbox"/>Check2<input type="checkbox"/>sub check 1</div>',
         1),
        ], ids=['no-indents', 'one-indent', 'invalid-indent-style', 'sibling indent with padding', 'sibling indent']
)
def test_find_indent(html, expected_indent):
    checklist_processor = checklist_processing.HTMLInputMDOutputChecklistProcessor(html)

    assert checklist_processor.list_of_checklist_items[2].indent == expected_indent


def test_enable_checklist_tags():
    html_content = '<div><input disabled type="checkbox"/>Check 1</div><div><input disabled type="checkbox"/>Check 1</div>'
    result = checklist_processing.enable_checklist_tags(html_content)
    expected = '<div><input type="checkbox"/>Check 1</div><div><input type="checkbox"/>Check 1</div>'
    assert result == expected